routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//Route::get('/', function () {
//    return view('welcome');
//});
Route::get('/', 'HomeController@index')->name('home');

Auth::routes();

Route::group(['middleware' => ['auth']], function () {
    Route::get('/home', 'HomeController@index')->name('home');
    Route::get('/dashboard', 'DashboardController@index');

    Route::resource('blog', 'BlogController');
});

app/Blog.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    protected $guarded=[];
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    protected $table = 'users';
    protected $primaryKey = 'id';


}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;
use Mockery\Exception;
use DB;


class BlogController extends Controller
{
    /**
     * Author Deepak Thakur
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     * version 1.0
     */
    public function index(Blog $blog){
        $blogs = $blog->all();
        return view('blog.index',compact('blogs'));
    }

    public function create()
    {
        return view('blog.create');
    }

    public function store(Blog $blog)
    {
        try{
            DB::beginTransaction();
            $inputs = request()->all();
            $inputs['user_id'] = userId();
            unset($inputs['_token']);
            if($blog->create($inputs)){
                DB::commit();
                return redirect(route('blog.index'));
            }
        }
        catch (Exception $e){
            DB::rollback();
        }
    }


}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    //
       public function index()
    {
        return view('dashboard');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Blog;
use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        //$this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Blog $blog)
    {
        $blogs = $blog->all();
        return view('frontent.home', compact('blogs'));
    }
}

resources/views/blog/create.blade.php
@extends('layouts.backend')

@section('content')
    <!-- Content Wrapper. Contains page content -->

    <section class="content">
        <div class="row">
            <!-- left column -->
            <div class="col-md-8">
                <!-- general form elements -->
                <div class="box box-primary">
                    <div class="box-header with-border">
                        <h3 class="box-title">Create Blog</h3>
                    </div>
                    <!-- /.box-header -->
                    <!-- form start -->
                    <form method="post" action="{{ route('blog.store') }}" role="form">
                        @csrf
                        <div class="box-body">
                            <div class="form-group">
                                <label for="exampleInputEmail1">Title</label>
                                <input name="title" type="text" class="form-control" id="title"
                                       placeholder="Enter Title" required>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputPassword1">Description</label>
                                <textarea required name="description"  class="form-control" id="exampleInputPassword1"
                                ></textarea>
                            </div>
                            <div class="form-group">
                                <label for="exampleInputFile">Featured image</label>
                                <input type="file" id="exampleInputFile">

                                <p class="help-block">Upload a image for this post</p>
                            </div>
                            <div class="checkbox">
                                <label>
                                    <input name="status" value="1" type="checkbox">Publish
                                </label>
                            </div>
                        </div>
                        <!-- /.box-body -->

                        <div class="box-footer">
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
                </div>


            </div>
        </div>
        <!-- /.row -->
    </section>



@endsection

resources/views/blog/index.blade.php
@extends('layouts.backend')

@section('content')
    <!-- Content Wrapper. Contains page content -->

    <section class="content">
        <div class="row">
            <div class="col-xs-12">
                <div class="box">
                    <div class="box-header">
                        <h3 class="box-title">My Blogs</h3>

                        <div class="box-tools">
                            <div class="input-group input-group-sm" style="width: 150px;">
                                <input type="text" name="table_search" class="form-control pull-right"
                                       placeholder="Search">

                                <div class="input-group-btn">
                                    <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.box-header -->
                    <div class="box-body table-responsive no-padding">
                        <table class="table table-hover">
                            <tr>
                                <th>ID</th>
                                <th>Title</th>
                                <th>Description</th>
                                <th>Status</th>
                                <th>Created At</th>
                            </tr>
                            @php
                            $i = 1;
                            @endphp
                            @foreach($blogs as $blog)
                                <tr>
                                    <td>{{$i++}}</td>
                                    <td>{{ $blog->title }}</td>
                                    <td>{{ $blog->description }}</td>
                                    <td><span class="label label-success">Published</span></td>
                                    <td>{{ $blog->created_at }}</td>
                                </tr>
                            @endforeach
                            @if(!count($blogs) >0)
                                <tr>
                                    <td>Record not Found.</td>
                                </tr>
                            @endif
                        </table>
                    </div>
                    <!-- /.box-body -->
                </div>
                <!-- /.box -->
            </div>
        </div>
    </section>



@endsection

resources/views/dashboard.blade.php
@extends('layouts.backend')

@section('content')
  <!-- Content Wrapper. Contains page content -->
 
    <section class="content-header">
      <h1>
        Dashboard
      </h1>
      <ol class="breadcrumb">
        <li><a href="#"><i class="fa fa-dashboard"></i> Home</a></li>
        <li class="active">Dashboard</li>
      </ol>
    </section>

    <!-- Main content -->
    <section class="content">
      <!-- Info boxes -->
      <div class="row">
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-aqua"><i class="ion ion-ios-gear-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Traffic</span>
              <span class="info-box-number">90<small>%</small></span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-red"><i class="fa fa-google-plus"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Likes</span>
              <span class="info-box-number">41,410</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->

        <!-- fix for small devices only -->
        <div class="clearfix visible-sm-block"></div>

        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-green"><i class="ion ion-ios-cart-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Read Articles</span>
              <span class="info-box-number">760</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
        <div class="col-md-3 col-sm-6 col-xs-12">
          <div class="info-box">
            <span class="info-box-icon bg-yellow"><i class="ion ion-ios-people-outline"></i></span>

            <div class="info-box-content">
              <span class="info-box-text">Page Viwers</span>
              <span class="info-box-number">2,000</span>
            </div>
            <!-- /.info-box-content -->
          </div>
          <!-- /.info-box -->
        </div>
        <!-- /.col -->
      </div>
      <!-- /.row -->




    </section>
    <!-- /.content -->

@endsection

resources/views/frontent/home.blade.php
@extends('layouts.frontend')

@section('content')
    <div id="content-wrap" class="container">
        <div class="row">
            <div id="content">
                <div class="sc">
                    <div class="row spb lat2">
                        <div class="col-md-12">
                            <a class="va" href="https://blog.bulletproof.com/category/article/">View all Articles +</a>
                            <h3>Latest Articles</h3>
                        </div>
                        <div class="flex-pt gridm">
                            @foreach($blogs as $blog)
                            <a class="sub col-md-6" href="#"
                               style="background-image:url(https://44uc8dkwa8q3f5b66w13vilg-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/leftovers_header-734x400.jpg);">
                                <div class="sdw"></div>
                                <div class="ico ib is i-artb ctrm"></div>
                                <div class="con">
                                    <h2 class="w700">{{ $blog->description }}</h2>
                                    <span>Article</span>
                                </div>
                            </a>
                            @endforeach
                        </div>
                    </div>
                    <div class="row spb cur">
                        <div class="col-md-12">
                            <h3>Most Read</h3>
                        </div>
                        <div class="flex-pt gridm">
                            <a class="sub col-md-4"
                               href="https://blog.bulletproof.com/how-to-make-your-coffee-bulletproof-and-your-morning-too/"
                               style="background-image:url(https://44uc8dkwa8q3f5b66w13vilg-wpengine.netdna-ssl.com/wp-content/uploads/2018/07/new-new-bp-header_V1-734x542.jpg);">
                                <div class="sdw"></div>
                                <div class="ico ib is i-artb ctrm"></div>
                                <div class="con">
                                    <h2 class="w700">How to Make Bulletproof Coffee … And Make Your Morning
                                        Bulletproof</h2>
                                    <span>Article</span><span>Featured</span>
                                </div>
                            </a>
                            <a class="sub col-md-4" href="https://blog.bulletproof.com/intermittent-fasting-guide/"
                               style="background-image:url(https://44uc8dkwa8q3f5b66w13vilg-wpengine.netdna-ssl.com/wp-content/uploads/2018/04/The-Incredible-Benefits-Intermittent-Fasting_header.jpg);">
                                <div class="sdw"></div>
                                <div class="ico ib is i-artb ctrm"></div>
                                <div class="con">
                                    <h2 class="w700">The Intermittent Fasting Guide for Beginners</h2>
                                    <span>Article</span><span>Featured</span>
                                </div>
                            </a>
                            <a class="sub col-md-4" href="https://blog.bulletproof.com/survey-win-200-credit/"
                               style="background-image:url(https://44uc8dkwa8q3f5b66w13vilg-wpengine.netdna-ssl.com/wp-content/uploads/2018/11/survey-giftcards-header-734x542.jpg);">
                                <div class="sdw"></div>
                                <div class="ico ib is i-b ctrm"></div>
                                <div class="con">
                                    <h2 class="w700">Enter to Win a $200 Store Credit to Bulletproof.com</h2>
                                    <span></span><span>Featured</span>
                                </div>
                            </a>
                        </div>
                    </div>



                    <div class="row mini">
                        <div class="col-md-4">
                            <h3>More Articles</h3>
                            <div class="shr"></div>
                            <a class="rel wys" href="https://blog.bulletproof.com/dark-roast-coffee-brain-study/">
                                <img src="img/This-Is-Your-Brain-On-Coffee_How-much-coffee-is-too-much-75x75.jpg"
                                     width="68" height="68">
                                <h2>Dark Roast Coffee May Reduce Risk of Alzheimer’s and Parkinson’s, Study Says</h2>
                                <p>Article</p>
                            </a>
                            <a class="rel wys" href="https://blog.bulletproof.com/sugar-cravings-challenge/">
                                <img src="img/Everything-You-Know-About-Cholesterol-Is-Wrong_Avoiding-sugar-and-excess-carbs-75x75.jpg"
                                     width="68" height="68">
                                <h2>The 30-Day No Sugar Challenge: A Step-by-Step Guide To Ending Sugar Cravings</h2>
                                <p>Article</p>
                            </a>
                            <a class="rel wys" href="https://blog.bulletproof.com/gout-diet-natural-remedies/">
                                <img src="img/Why-Gout-is-On-The-Rise-and-How-Your-Diet-Plays-a-Part-in-Symptoms_header-75x75.jpg"
                                     width="68" height="68">
                                <h2>Why Gout Is On The Rise and How Your Diet Plays a Part in Symptoms</h2>
                                <p>Article</p>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <h3>More Podcasts</h3>
                            <div class="shr"></div>
                            <a class="rel wys" href="https://blog.bulletproof.com/bob-hariri-539/">
                                <img src="img/BobHariri-75x75.jpg" width="68" height="68">
                                <h2>100 Years Old is the New 60 – Dr. Bob Hariri #539</h2>
                                <p>Podcast</p>
                            </a>
                            <a class="rel wys" href="https://blog.bulletproof.com/eric-kandel-538/">
                                <img src="img/kandel-75x75.jpg" width="68" height="68">
                                <h2>The Unusual Brain of Dr. Eric Kandel #538</h2>
                                <p>Podcast</p>
                            </a>
                            <a class="rel wys" href="https://blog.bulletproof.com/charles-poliquin-537/">
                                <img src="img/sensei_smile-75x75.jpg" width="68" height="68">
                                <h2>Special Edition: Aerobic Exercise May Be Destroying Your Body – Charles Poliquin
                                    #537</h2>
                                <p>Podcast</p>
                            </a>
                        </div>
                        <div class="col-md-4">
                            <h3>More Recipes</h3>
                            <div class="shr"></div>
                            <a class="rel wys"
                               href="https://blog.bulletproof.com/cranberry-orange-muffins-recipe-keto-2g/">
                                <img src="img/cran-orange-muffins_header-75x75.jpg" width="68" height="68">
                                <h2>Keto Cranberry Orange Muffins</h2>
                                <p>Recipe</p>
                            </a>
                            <a class="rel wys" href="https://blog.bulletproof.com/sweet-potato-gratin-recipe-paleo-2g/">
                                <img src="img/Sweet-Potato-Gratin_header-75x75.jpg" width="68" height="68">
                                <h2>Paleo Sweet Potato Gratin</h2>
                                <p>Recipe</p>
                            </a>
                            <a class="rel wys" href="https://blog.bulletproof.com/air-fryer-recipes-paleo-2g/">
                                <img src="img/21-Air-Fryer-Recipes-for-All-Your-Fried-Food-Cravings_header-75x75.jpg"
                                     width="68" height="68">
                                <h2>21 Air Fryer Recipes for All Your Fried Food Cravings</h2>
                                <p>Recipe</p>
                            </a>
                        </div>
                    </div>
                    <div class="row mdia">
                        <div class="col-md-12">
                            <h3>Media Type</h3>
                        </div>
                        <div class="col-md-12">
                            <a href="https://blog.bulletproof.com/category/article/" class="media-type">
                                <div class="ico imt i-artc ctrm"></div>
                                <span>Articles</span>
                            </a>
                            <a href="https://blog.bulletproof.com/category/podcasts/" class="media-type">
                                <div class="ico imt i-podc ctrm"></div>
                                <span>Podcasts</span>
                            </a>
                            <a href="https://blog.bulletproof.com/category/video/" class="media-type">
                                <div class="ico imt i-vidc ctrm"></div>
                                <span>Videos</span>
                            </a>
                            <a href="https://blog.bulletproof.com/category/infographic/" class="media-type">
                                <div class="ico imt i-infc ctrm"></div>
                                <span>Infographics</span>
                            </a>
                            <a href="https://blog.bulletproof.com/category/recipes/" class="media-type">
                                <div class="ico imt i-recc ctrm"></div>
                                <span>Recipes</span>
                            </a>
                            <div class="clear"></div>
                        </div>
                    </div>
                    <div class="row spb sctag">
                        <div class="col-md-12">
                            <h3>Popular Topics</h3>
                        </div>
                        <div class="tags col-md-12">
                            <a href="https://blog.bulletproof.com/tag/biohacking/">biohacking</a><a
                                    href="https://blog.bulletproof.com/tag/bulletproof-diet/">Bulletproof Diet</a><a
                                    href="https://blog.bulletproof.com/tag/gluten-free/">gluten-free</a><a
                                    href="https://blog.bulletproof.com/tag/sugar-free/">sugar-free</a><a
                                    href="https://blog.bulletproof.com/tag/diet/">Diet</a><a
                                    href="https://blog.bulletproof.com/tag/nutrition/">nutrition</a><a
                                    href="https://blog.bulletproof.com/tag/performance/">Performance</a><a
                                    href="https://blog.bulletproof.com/tag/brain/">brain</a><a
                                    href="https://blog.bulletproof.com/tag/cognitive-enhancement/">cognitive
                                enhancement</a><a href="https://blog.bulletproof.com/tag/vegetarian/">vegetarian</a><a
                                    href="https://blog.bulletproof.com/tag/fat-burning/">fat burning</a><a
                                    href="https://blog.bulletproof.com/tag/healthy-fat/">healthy fat</a><a
                                    href="https://blog.bulletproof.com/tag/stress/">stress</a><a
                                    href="https://blog.bulletproof.com/tag/supplements/">supplements</a><a
                                    href="https://blog.bulletproof.com/tag/fat/">fat</a><a
                                    href="https://blog.bulletproof.com/tag/toxins/">toxins</a><a
                                    href="https://blog.bulletproof.com/tag/sleep/">sleep</a><a
                                    href="https://blog.bulletproof.com/tag/food/">food</a><a
                                    href="https://blog.bulletproof.com/tag/chocolate/">Chocolate</a>
                            <div class="clear"></div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="clear"></div>
        </div>
    </div>
    <div class="clear"></div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                    {{ config('app.name', 'Laravel') }}
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            <li class="nav-item">
                                @if (Route::has('register'))
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                @endif
                            </li>
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/layouts/backend.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <!-- <link href="{{ asset('css/app.css') }}" rel="stylesheet"> -->
    <link rel="dns-prefetch" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

     <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">
      <!-- Font Awesome -->
      <link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}">
      <!-- Ionicons -->
      <link rel="stylesheet" href="{{asset('css/ionicons.min.css')}}">
      <!-- jvectormap -->
      <link rel="stylesheet" href="{{asset('css/jquery-jvectormap.css')}}">
      <!-- Theme style -->
      <link rel="stylesheet" href="{{asset('css/AdminLTE.min.css')}}">
      <!-- AdminLTE Skins. Choose a skin from the css/skins
           folder instead of downloading all of them to reduce the load. -->
      <link rel="stylesheet" href="{{asset('css/_all-skins.min.css')}}">
  <link rel="stylesheet"
        href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <!-- Styles -->

  
</head>
<body class="hold-transition skin-blue sidebar-mini">

    <div class="wrapper" id="backend">
         @include('layouts.sidebar')
         @include('layouts.header')

       

         <div class="content-wrapper">

            @yield('content')
        </div>
         @include('layouts.footer')
    </div>
    
    <script src="{{ asset('js/jquery-3.2.1.min.js')}}"></script>
<!-- Bootstrap 3.3.7 -->
<script src="{{ asset('js/bootstrap.min.js')}}"></script>
<!-- FastClick -->
<script src="{{ asset('js/fastclick.js')}} "></script>
<!-- AdminLTE App -->
<script src="{{ asset('js/adminlte.min.js')}}"></script>
<!-- Sparkline -->
<script src="{{ asset('js/jquery.sparkline.min.js')}} "></script>
<!-- jvectormap  -->
<script src="{{ asset('js/jquery-jvectormap-1.2.2.min.js')}} "></script>
<script src="{{ asset('js/jquery-jvectormap-world-mill-en.js')}}"></script>
<!-- SlimScroll -->
<script src="{{ asset('js/jquery.slimscroll.min.js')}} "></script>
<!-- ChartJS -->
<script src="{{ asset('js/Chart.js')}} "></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{ asset('js/dashboard2.js')}} "></script>
<!-- AdminLTE for demo purposes -->
<script src="{{ asset('js/demo.js')}}"></script>
</body>
<!-- jQuery 3 -->

</html>

resources/views/layouts/footer.blade.php
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b>
    </div>
    <strong>Copyright &copy; 2019 <a href="#">Simpleitis</a>.</strong> All rights
    reserved.
  </footer>

resources/views/layouts/newfooter.blade.php
 <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>